spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8000

eureka:
#  server:
#    enable-self-preservation: false           #关闭自我保护机制，防止显示在线的客户端不准确
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
