spring:
  application:
    name: zuul

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    instance_id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  routes:
    storage:
      path: /storage/**
      serviceId: storage
    order:
      path: /order/**
      serviceId: order
    storage-url:
      path: /storage-url/**
      url: http://127.0.0.1:8081/