spring:
  application:
    name: order

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    instance_id: ${spring.cloud.client.ip-address}:${server.port}
